# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test ./Lineup.Coach.Application.Tests
    dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactsStagingDirectory)

- task: PublishTestResults@2
  condition: succeeded()
  continueOnError: true
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifiactsStagingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
