import{test}from'node:test';import assert from'node:assert/strict';import{generate,validate,audit,swap}from'../src/engine';import type{Input}from'../src/model';
export function fixture(n=9,positions=6,periods=4):Input{const slots=Array.from({length:positions},(_,i)=>({id:`s${i}`,name:`Position ${i}`}));return{players:Array.from({length:n},(_,i)=>({id:`p${i}`,firstName:'Same',lastName:String(i),ranking:[slots[i%positions].id,slots[(i+1)%positions].id],excluded:[]})),positions:slots,periods,locks:[],seed:42}}
test('one unique assignment per present player per period, including same-name players',()=>{for(let n=6;n<=18;n++){const input=fixture(n);const a=generate(input);assert.deepEqual(validate(input,a),[]);assert.ok(audit(input,a).benchSpread<=1)}});
test('hard exclusions and locks hold for every returned lineup',()=>{const input=fixture();input.players[0].excluded=['s0','s1','s2'];input.locks=[{period:0,positionId:'s3',playerId:'p0'}];const a=generate(input);assert.deepEqual(validate(input,a),[]);assert.equal(a.find(x=>x.period===0&&x.positionId==='s3')?.playerId,'p0')});
test('impossible exclusions never return an invalid result',()=>{const input=fixture(6);input.players.forEach(p=>p.excluded=['s0']);assert.throws(()=>generate(input),/No valid lineup/)});
test('conflicting and unavailable locks fail explicitly',()=>{const input=fixture();input.locks=[{period:0,positionId:'s0',playerId:'p0'},{period:0,positionId:'s1',playerId:'p0'}];assert.throws(()=>generate(input),/lock/);input.locks=[{period:0,positionId:'s0',playerId:'absent'}];assert.throws(()=>generate(input),/lock/)});
test('insufficient attendance is rejected; no silently empty field positions',()=>assert.throws(()=>generate(fixture(5)),/need at least/));
test('deterministic inputs yield deterministic results',()=>assert.deepEqual(generate(fixture()),generate(fixture())));
test('valid swaps preserve uniqueness; locked and excluded swaps are rejected',()=>{const input=fixture(),a=generate(input),first=a[0],second=a[1];const b=swap(input,a,0,first.positionId,second.playerId);assert.equal(b[0].playerId,second.playerId);assert.deepEqual(validate(input,b),[]);assert.notEqual(a[0].playerId,b[0].playerId);input.locks=[{period:0,positionId:first.positionId,playerId:first.playerId}];assert.throws(()=>swap(input,a,0,first.positionId,second.playerId),/locked/);input.locks=[];input.players.find(p=>p.id===second.playerId)!.excluded=[first.positionId];assert.throws(()=>swap(input,a,0,first.positionId,second.playerId),/excluded/)});
test('boundary: 40 players and 12 periods, all positions filled',()=>{const input=fixture(40,22,12),a=generate(input);assert.deepEqual(validate(input,a),[])});
