import {useState} from 'react';
import {Alert,Button,Checkbox,FormControlLabel,MenuItem,TextField} from '@mui/material';
import {newGame,uid,type Team,type Game,type Player} from './model';
import {parseRoster,duplicateNames,nameKey} from './roster';
const defaultPositions=['Goalkeeper','Left defender','Right defender','Left midfield','Right midfield','Striker'];
export default function TeamSetup({onSave,onCancel,saving,error}:{onSave:(team:Team,game:Game,generate:boolean)=>Promise<void>;onCancel?:()=>void;saving:boolean;error:string}){
 const [step,setStep]=useState(0),[name,setName]=useState(''),[positions,setPositions]=useState(defaultPositions),[rows,setRows]=useState<Player[]>([]),[paste,setPaste]=useState(''),[notice,setNotice]=useState(''),[absent,setAbsent]=useState<string[]>([]);
 const [opponent,setOpponent]=useState(''),[date,setDate]=useState(()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`}),[time,setTime]=useState(''),[periods,setPeriods]=useState(4),[minutes,setMinutes]=useState(12);
 const duplicates=duplicateNames(rows),present=rows.length-absent.length;
 const teamValid=!!name.trim()&&positions.every(p=>p.trim())&&new Set(positions.map(p=>p.trim().toLowerCase())).size===positions.length;
 const rosterValid=rows.length>0&&rows.length<=40&&rows.every(p=>p.firstName.trim());
 const gameValid=!!opponent.trim()&&!!date&&Number.isInteger(periods)&&periods>=1&&periods<=12&&Number.isInteger(minutes)&&minutes>=1&&minutes<=60;
 function resize(count:number){if(!Number.isInteger(count)||count<1||count>22)return;setPositions(current=>Array.from({length:count},(_,i)=>current[i]??defaultPositions[i]??`Position ${i+1}`));setRows(current=>current.map(p=>({...p,ranking:p.ranking.filter(id=>Number(id)<count),excluded:p.excluded.filter(id=>Number(id)<count)})))}
 function update(id:string,edit:Partial<Player>){setRows(rows.map(p=>p.id===id?{...p,...edit}:p))}
 async function save(generate:boolean){const slots=positions.map(name=>({id:uid(),name:name.trim()}));const team:Team={id:uid(),name:name.trim(),positions:slots,players:rows.map(p=>({...p,firstName:p.firstName.trim(),lastName:p.lastName.trim(),ranking:p.ranking.map(id=>slots[Number(id)]?.id).filter(id=>!!id),excluded:p.excluded.map(id=>slots[Number(id)]?.id).filter(id=>!!id)}))};
 const game={...newGame(team,opponent.trim()),date,time,periods,minutes,attendance:Object.fromEntries(rows.map(p=>[p.id,!absent.includes(p.id)]))};await onSave(team,game,generate)}
 return <main className="workspace"><section className="surface team-setup"><header><p className="crumb">NEW TEAM · STEP {step+1} OF 3</p><h1>{['Create your team','Add your roster','Set up your first game'][step]}</h1><p className="subhead">{['Use the default positions or edit them for your team.','Paste or type names, then review your roster below.','Check attendance and generate your first lineup.'][step]}</p></header>
 <ol className="setup-progress" aria-label="Setup progress">{['Team','Players','Game'].map((label,i)=><li key={label} aria-current={step===i?'step':undefined}>{i+1}. {label}</li>)}</ol>
 <fieldset disabled={saving} className="main-fieldset setup-fields">{error&&<Alert severity="error">{error}</Alert>}
 {step===0&&<><TextField label="Team name" autoFocus required value={name} onChange={e=>setName(e.target.value)}/><TextField select label="Players on the field" helperText="Includes the goalkeeper. Bench players are extra. Existing positions stay in order; reducing the count removes positions from the end." value={positions.length} onChange={e=>resize(Number(e.target.value))}>{Array.from({length:22},(_,i)=><MenuItem key={i+1} value={i+1}>{`${i+1} ${i===0?'player':'players'}`}</MenuItem>)}</TextField><details><summary>Edit field positions</summary><div className="setup-position-grid">{positions.map((p,i)=><TextField key={i} label={`Position ${i+1}`} value={p} error={!p.trim()||positions.some((other,j)=>j!==i&&other.trim().toLowerCase()===p.trim().toLowerCase())} onChange={e=>setPositions(positions.map((v,j)=>j===i?e.target.value:v))}/>)}</div></details><p className="helper">{positions.join(' · ')}. Bench spots are added automatically.</p>{!teamValid&&<p className="helper">Enter a team name and use a different name for every field position.</p>}</>}
 {step===1&&<><TextField label="Paste or type player names" multiline minRows={4} placeholder={'Alex Morgan\nJordan Lee\nTaylor Brooks'} helperText="Type one full name per line, paste a list, or paste first and last name columns from a spreadsheet (without headers). You can also add players individually below. Up to 40 players." value={paste} onChange={e=>setPaste(e.target.value)}/><Button variant="outlined" disabled={!paste.trim()} onClick={()=>{const parsed=parseRoster(paste);if(parsed.length+rows.length>40){setNotice('This would exceed 40 players. Remove some names before adding.');return}setRows([...rows,...parsed.map(p=>({...p,id:uid(),ranking:[],excluded:[]}))]);setPaste('');setNotice('')}}>Add names to roster</Button>{notice&&<Alert severity="warning">{notice}</Alert>}<h2>Roster · {rows.length} players</h2>{duplicates.size>0&&<Alert severity="warning">Repeated names are highlighted. Edit or remove accidental duplicates; players with the same name can stay.</Alert>}{rows.map((p,i)=><div className="setup-player" key={p.id}><TextField label={`Player ${i+1} first name`} required value={p.firstName} error={!p.firstName.trim()||duplicates.has(nameKey(p))} onChange={e=>update(p.id,{firstName:e.target.value})}/><TextField label="Last name" value={p.lastName} onChange={e=>update(p.id,{lastName:e.target.value})}/><Button aria-label={`Remove player ${i+1}`} onClick={()=>{setRows(rows.filter(row=>row.id!==p.id));setAbsent(absent.filter(id=>id!==p.id))}}>Remove</Button></div>)}<Button disabled={rows.length>=40} onClick={()=>setRows([...rows,{id:uid(),firstName:'',lastName:'',ranking:[],excluded:[]}])}>Add one player</Button><details><summary>Player preferences (optional)</summary>
 <p className="helper">Add preferred positions in order, with the favorite first. Unranked positions remain available. Mark positions a player cannot play under exclusions.</p>
 <div className="setup-fields">{rows.map((p,i)=><details className="setup-preferences" key={p.id}>
 <summary>{`${p.firstName||`Player ${i+1}`} ${p.lastName}`.trim()} · {p.ranking.length} ranked · {p.excluded.length} excluded</summary>
 <div className="setup-fields">
 {p.ranking.length===0&&<p className="helper">No preferences yet — all non-excluded positions are equally preferred.</p>}
 <ol className="setup-ranking">{p.ranking.map((id,index)=><li key={id}>
 <span>{index+1}. {positions[Number(id)]}</span><div className="setup-rank-actions">
 <Button size="small" aria-label={`Move ${positions[Number(id)]} up for player ${i+1}`} disabled={index===0} onClick={()=>{const ranking=[...p.ranking];[ranking[index-1],ranking[index]]=[ranking[index],ranking[index-1]];update(p.id,{ranking})}}>Up</Button>
 <Button size="small" aria-label={`Move ${positions[Number(id)]} down for player ${i+1}`} disabled={index===p.ranking.length-1} onClick={()=>{const ranking=[...p.ranking];[ranking[index+1],ranking[index]]=[ranking[index],ranking[index+1]];update(p.id,{ranking})}}>Down</Button>
 <Button size="small" aria-label={`Remove ${positions[Number(id)]} preference for player ${i+1}`} onClick={()=>update(p.id,{ranking:p.ranking.filter(value=>value!==id)})}>Remove</Button>
 </div></li>)}</ol>
 <TextField select label={`Add preference for player ${i+1}`} value="" disabled={p.ranking.length+p.excluded.length===positions.length} onChange={e=>update(p.id,{ranking:[...p.ranking,e.target.value]})}>{positions.map((pos,j)=>({pos,id:String(j)})).filter(({id})=>!p.ranking.includes(id)&&!p.excluded.includes(id)).map(({pos,id})=><MenuItem key={id} value={id}>{pos}</MenuItem>)}</TextField>
 <details><summary>Cannot play · {p.excluded.length} excluded</summary><div className="setup-attendance">{positions.map((pos,j)=><FormControlLabel key={j} label={pos} control={<Checkbox checked={p.excluded.includes(String(j))} onChange={e=>update(p.id,{excluded:e.target.checked?[...p.excluded,String(j)]:p.excluded.filter(id=>id!==String(j)),ranking:e.target.checked?p.ranking.filter(id=>id!==String(j)):p.ranking})}/>}/>)}</div></details>
 </div></details>)}</div></details></>}
 {step===2&&<><TextField label="Opponent / game name" required value={opponent} onChange={e=>setOpponent(e.target.value)}/><div className="setup-position-grid"><TextField label="Date" type="date" required InputLabelProps={{shrink:true}} value={date} onChange={e=>setDate(e.target.value)}/><TextField label="Time (optional)" type="time" InputLabelProps={{shrink:true}} value={time} onChange={e=>setTime(e.target.value)}/><TextField label="Periods" type="number" inputProps={{min:1,max:12}} value={periods} error={!Number.isInteger(periods)||periods<1||periods>12} onChange={e=>setPeriods(Number(e.target.value))}/><TextField label="Minutes per period" type="number" inputProps={{min:1,max:60}} value={minutes} error={!Number.isInteger(minutes)||minutes<1||minutes>60} onChange={e=>setMinutes(Number(e.target.value))}/></div><details><summary>Attendance · {present} of {rows.length} present</summary><div className="setup-attendance">{rows.map(p=><FormControlLabel key={p.id} label={`${p.firstName} ${p.lastName}`} control={<Checkbox checked={!absent.includes(p.id)} onChange={e=>setAbsent(e.target.checked?absent.filter(id=>id!==p.id):[...absent,p.id])}/>}/>)}</div></details><p className="setup-review">{present} present · {positions.length} field positions · {periods} periods</p>{present<positions.length&&<Alert severity="warning">You need {positions.length-present} more present players to fill the field. Go back to add players or reduce field positions. You can also save and finish later.</Alert>}{!gameValid&&<p className="helper">Enter an opponent and date, 1–12 periods, and 1–60 minutes per period.</p>}</>}
 <div className="setup-navigation">{step>0?<Button onClick={()=>setStep(step-1)}>Back</Button>:onCancel&&<Button onClick={onCancel}>Cancel</Button>}{step<2?<Button variant="contained" disabled={step===0?!teamValid:!rosterValid||!!paste.trim()} onClick={()=>setStep(step+1)}>Continue</Button>:<><Button disabled={!gameValid} onClick={()=>void save(false)}>Save and finish later</Button><Button variant="contained" disabled={!gameValid||present<positions.length} onClick={()=>void save(true)}>{saving?'Saving…':'Generate lineup'}</Button></>}</div>{step===1&&!!paste.trim()&&<p className="helper">Add the names you typed or pasted to the roster before continuing.</p>}
 </fieldset></section></main>
}
